/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import controller.*;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author V E N U R I
 */
public class VFlight_Details extends javax.swing.JFrame {

    /**
     * Creates new form VFlight_Details
     */
    public VFlight_Details() {
        initComponents();
        
        cmbFrom.setSelectedIndex(-1); 
        cmbTo.setSelectedIndex(-1);
        
        Image icon = new ImageIcon(this.getClass().getResource("/logo.png")).getImage();
        this.setIconImage(icon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFlightNumber = new javax.swing.JTextField();
        cmbTo = new javax.swing.JComboBox<>();
        cmbFrom = new javax.swing.JComboBox<>();
        datecArrivalDate = new com.toedter.calendar.JDateChooser();
        datecDepartureDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Details");

        jPanel1.setBackground(new java.awt.Color(0, 0, 122));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(95, 184, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Full Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("From");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("To");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Departure Date");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Arrival Date");

        txtFlightNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cmbTo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Melbourne Airport (MEL) - Australia", "Sydney Kingsford Smith Airport (SYD) - Australia", "Hazrat Shahjalal International Airport (DAC) - Bangladesh", "Beijing Capital International Airport (PEK) - China", "Guangzhou Baiyun International Airport (CAN) - China", "Charles de Gaulle Airport (CDG) - France", "Frankfurt am Main Airport (FRA) - Germany", "Chhatrapati Shivaji Maharaj International Airport (BOM) - India", "Chennai International Airport (MAA) - India", "Indira Gandhi International Airport (DEL) - India", "Kempegowda International Airport (BLR) - India", "Netaji Subhas Chandra Bose International Airport (CCU) - India", "Leonardo da Vinci International Airport (FCO) - Italy", "Malpensa Airport (MXP) - Italy", "Kansai International Airport (KIX) - Japan", "Narita International Airport (NRT) - Japan", "Kuwait International Airport (KWI) - Kuwait", "Kuala Lumpur International Airport (KUL) - Malaysia", "Velana International Airport (MLE) - Maldives", "Tribhuvan International Airport (KTM) - Nepal", "Allama Iqbal International Airport (LHE) - Pakistan", "Jinnah International Airport (KHI) - Pakistan", "Hamad International Airport (DOH) - Qatar", "Sheremetyevo International Airport (SVO) - Russia", "King Abdulaziz International Airport (JED) - Saudi Arabia", "King Khalid International Airport (RUH) - Saudi Arabia", "Changi International Airport (SIN) - Singapore", "O.R. Tambo International Airport (JNB) - South Africa", "Bandaranaike International Airport (CMB) - Sri Lanka", "China Bay Airport (TRR) - Sri Lanka", "Jaffna International Airport (JAF) - Sri Lanka", "Mattala Rajapaksa International Airport (HRI) - Sri Lanka", "Victoria Reservoir Airfield (KDZ) -Sri Lanka", "Suvarnabhumi Airport (BKK) - Thailand", "Heathrow Airport (LHR) - United Kingdom", "Abu Dhabi International Airport (AUH) - UAE", "Dubai International Airport (DXB) - UAE" }));

        cmbFrom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Melbourne Airport (MEL) - Australia", "Sydney Kingsford Smith Airport (SYD) - Australia", "Hazrat Shahjalal International Airport (DAC) - Bangladesh", "Beijing Capital International Airport (PEK) - China", "Guangzhou Baiyun International Airport (CAN) - China", "Charles de Gaulle Airport (CDG) - France", "Frankfurt am Main Airport (FRA) - Germany", "Chhatrapati Shivaji Maharaj International Airport (BOM) - India", "Chennai International Airport (MAA) - India", "Indira Gandhi International Airport (DEL) - India", "Kempegowda International Airport (BLR) - India", "Netaji Subhas Chandra Bose International Airport (CCU) - India", "Leonardo da Vinci International Airport (FCO) - Italy", "Malpensa Airport (MXP) - Italy", "Kansai International Airport (KIX) - Japan", "Narita International Airport (NRT) - Japan", "Kuwait International Airport (KWI) - Kuwait", "Kuala Lumpur International Airport (KUL) - Malaysia", "Velana International Airport (MLE) - Maldives", "Tribhuvan International Airport (KTM) - Nepal", "Allama Iqbal International Airport (LHE) - Pakistan", "Jinnah International Airport (KHI) - Pakistan", "Hamad International Airport (DOH) - Qatar", "Sheremetyevo International Airport (SVO) - Russia", "King Abdulaziz International Airport (JED) - Saudi Arabia", "King Khalid International Airport (RUH) - Saudi Arabia", "Changi International Airport (SIN) - Singapore", "O.R. Tambo International Airport (JNB) - South Africa", "Bandaranaike International Airport (CMB) - Sri Lanka", "China Bay Airport (TRR) - Sri Lanka", "Jaffna International Airport (JAF) - Sri Lanka", "Mattala Rajapaksa International Airport (HRI) - Sri Lanka", "Victoria Reservoir Airfield (KDZ) -Sri Lanka", "Suvarnabhumi Airport (BKK) - Thailand", "Heathrow Airport (LHR) - United Kingdom", "Abu Dhabi International Airport (AUH) - UAE", "Dubai International Airport (DXB) - UAE" }));
        cmbFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFromActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Delete");

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datecArrivalDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFlightNumber)
                    .addComponent(cmbFrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(datecDepartureDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datecDepartureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datecArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFromActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    try 
        {
            String flightNumber;
            String fromDestination;
            String toDestination;
            String departureDate;
            String arrivalDate;

            flightNumber = txtFlightNumber.getText();
            if (flightNumber.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Flight number is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            fromDestination=cmbFrom.getSelectedItem().toString();
            toDestination=cmbTo.getSelectedItem().toString();
            if (fromDestination.equals("--Select--") || toDestination.equals("--Select--")) 
            {
                JOptionPane.showMessageDialog(this, "Please select valid destinations.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (fromDestination.equals(toDestination)) 
            {
                JOptionPane.showMessageDialog(this, "From and To destinations cannot be the same.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            departureDate = sdf.format(datecDepartureDate.getDate());
            arrivalDate = sdf.format(datecArrivalDate.getDate());
            if (datecDepartureDate.getDate() == null || datecArrivalDate.getDate() == null) 
            {
                JOptionPane.showMessageDialog(this, "Both departure and arrival dates are required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (datecDepartureDate.getDate().after(datecArrivalDate.getDate())) 
            {
                JOptionPane.showMessageDialog(this, "Departure date cannot be after arrival date.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            CFlight_Details fli_add = new CFlight_Details();
            fli_add.addFlightDetails(flightNumber, fromDestination, toDestination, departureDate, arrivalDate);
            JOptionPane.showMessageDialog(this, "Flight details added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Add Error", JOptionPane.ERROR_MESSAGE);
        }
        
        clearForm();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try 
        {
            String flightNumber;
            String fromDestination;
            String toDestination;
            String departureDate;
            String arrivalDate;

            flightNumber = txtFlightNumber.getText();
            if (flightNumber.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Flight number is required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (cmbFrom.getSelectedIndex() == -1 || cmbTo.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Please select both 'From' and 'To' destinations.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            fromDestination = cmbFrom.getSelectedItem().toString();
            toDestination = cmbTo.getSelectedItem().toString();

            if (fromDestination.equals(toDestination)) {
                JOptionPane.showMessageDialog(this, "From and To destinations cannot be the same.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            if (datecDepartureDate.getDate() == null || datecArrivalDate.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Both departure and arrival dates are required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            departureDate = sdf.format(datecDepartureDate.getDate());
            arrivalDate = sdf.format(datecArrivalDate.getDate());

            if (datecDepartureDate.getDate().after(datecArrivalDate.getDate())) {
                JOptionPane.showMessageDialog(this, "Departure date cannot be after arrival date.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }


            CFlight_Details fli_update = new CFlight_Details();
            fli_update.updateFlightDetails(flightNumber, fromDestination, toDestination, departureDate, arrivalDate);
            JOptionPane.showMessageDialog(this, "Flight details updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Update Error", JOptionPane.ERROR_MESSAGE);
        }

        clearForm();
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VFlight_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VFlight_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VFlight_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VFlight_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VFlight_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbFrom;
    private javax.swing.JComboBox<String> cmbTo;
    private com.toedter.calendar.JDateChooser datecArrivalDate;
    private com.toedter.calendar.JDateChooser datecDepartureDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtFlightNumber;
    // End of variables declaration//GEN-END:variables

    private void clearForm() 
    {
        txtFlightNumber.setText("");
        cmbFrom.setSelectedIndex(-1);
        cmbTo.setSelectedIndex(-1);
        datecDepartureDate.setDate(null);
        datecArrivalDate.setDate(null); 
    }
}
