/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.*; 
import javax.swing.*; 
import java.awt.Image; 
import javax.swing.table.DefaultTableModel; 
import java.awt.event.ActionEvent; 
import java.awt.event.ActionListener; 
import java.text.SimpleDateFormat; 
import java.util.List;


public class VPassenger_View_Flight_Details extends javax.swing.JFrame 
{
    private static final String DEFAULT_SELECTION = "--Select--";
    private CPassenger_View_Flight_Details controller;
    
    
    public VPassenger_View_Flight_Details() 
    {
        initComponents();
        
        cmbFrom.setSelectedIndex(-1); 
        cmbTo.setSelectedIndex(-1);
        cmbClass.setSelectedIndex(-1);
        
        Image icon = new ImageIcon(this.getClass().getResource("/logo.png")).getImage();
        this.setIconImage(icon);
        
        controller = new CPassenger_View_Flight_Details();
        
        btnSearchFlight.addActionListener(this::btnSearchFlightActionPerformed);   
    }
    
    private void searchFlights() 
    {
        try 
        {
            String fromDestination = cmbFrom.getSelectedItem().toString();
            String toDestination = cmbTo.getSelectedItem().toString();
            String flightClass = cmbClass.getSelectedItem().toString();
            int passengers = (int) spPassengers.getValue();

            if (fromDestination.equals(DEFAULT_SELECTION) || toDestination.equals(DEFAULT_SELECTION) || fromDestination.equals(toDestination)) 
            {
                JOptionPane.showMessageDialog(this, "Please select valid destinations.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (flightClass.equals(DEFAULT_SELECTION) || passengers <= 0) 
            {
                JOptionPane.showMessageDialog(this, "All fields are required.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            List<Object[]> flightData = controller.getFlights(fromDestination, toDestination, flightClass, passengers);

            if (flightData == null || flightData.isEmpty()) 
            {
                JOptionPane.showMessageDialog(this, "No flights found.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
            } else {
                populateTable(flightData);
            }
        } 
        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Search Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void populateTable(List<Object[]> flightData)
    {
        DefaultTableModel model = (DefaultTableModel) tblFlights.getModel();
        model.setRowCount(0); 
        for (Object[] row : flightData) 
        {
            model.addRow(row); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnFlightDetails = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbFrom = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbClass = new javax.swing.JComboBox<>();
        spPassengers = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        btnSearchFlight = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFlights = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Details");

        jPanel1.setBackground(new java.awt.Color(0, 0, 122));
        jPanel1.setPreferredSize(new java.awt.Dimension(238, 690));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo4.png"))); // NOI18N

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnFlightDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFlightDetails.setText("Flight Details");
        btnFlightDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFlightDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnHome)
                .addGap(28, 28, 28)
                .addComponent(btnFlightDetails)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(95, 184, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(996, 690));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Flight Details");

        cmbFrom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbFrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Melbourne Airport (MEL) - Australia", "Sydney Kingsford Smith Airport (SYD) - Australia", "Hazrat Shahjalal International Airport (DAC) - Bangladesh", "Beijing Capital International Airport (PEK) - China", "Guangzhou Baiyun International Airport (CAN) - China", "Charles de Gaulle Airport (CDG) - France", "Frankfurt am Main Airport (FRA) - Germany", "Chhatrapati Shivaji Maharaj International Airport (BOM) - India", "Chennai International Airport (MAA) - India", "Indira Gandhi International Airport (DEL) - India", "Kempegowda International Airport (BLR) - India", "Netaji Subhas Chandra Bose International Airport (CCU) - India", "Leonardo da Vinci International Airport (FCO) - Italy", "Malpensa Airport (MXP) - Italy", "Kansai International Airport (KIX) - Japan", "Narita International Airport (NRT) - Japan", "Kuwait International Airport (KWI) - Kuwait", "Kuala Lumpur International Airport (KUL) - Malaysia", "Velana International Airport (MLE) - Maldives", "Tribhuvan International Airport (KTM) - Nepal", "Allama Iqbal International Airport (LHE) - Pakistan", "Jinnah International Airport (KHI) - Pakistan", "Hamad International Airport (DOH) - Qatar", "Sheremetyevo International Airport (SVO) - Russia", "King Abdulaziz International Airport (JED) - Saudi Arabia", "King Khalid International Airport (RUH) - Saudi Arabia", "Changi International Airport (SIN) - Singapore", "O.R. Tambo International Airport (JNB) - South Africa", "Bandaranaike International Airport (CMB) - Sri Lanka", "China Bay Airport (TRR) - Sri Lanka", "Jaffna International Airport (JAF) - Sri Lanka", "Mattala Rajapaksa International Airport (HRI) - Sri Lanka", "Victoria Reservoir Airfield (KDZ) -Sri Lanka", "Suvarnabhumi Airport (BKK) - Thailand", "Heathrow Airport (LHR) - United Kingdom", "Abu Dhabi International Airport (AUH) - UAE", "Dubai International Airport (DXB) - UAE" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("From");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("To");

        cmbTo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Melbourne Airport (MEL) - Australia", "Sydney Kingsford Smith Airport (SYD) - Australia", "Hazrat Shahjalal International Airport (DAC) - Bangladesh", "Beijing Capital International Airport (PEK) - China", "Guangzhou Baiyun International Airport (CAN) - China", "Charles de Gaulle Airport (CDG) - France", "Frankfurt am Main Airport (FRA) - Germany", "Chhatrapati Shivaji Maharaj International Airport (BOM) - India", "Chennai International Airport (MAA) - India", "Indira Gandhi International Airport (DEL) - India", "Kempegowda International Airport (BLR) - India", "Netaji Subhas Chandra Bose International Airport (CCU) - India", "Leonardo da Vinci International Airport (FCO) - Italy", "Malpensa Airport (MXP) - Italy", "Kansai International Airport (KIX) - Japan", "Narita International Airport (NRT) - Japan", "Kuwait International Airport (KWI) - Kuwait", "Kuala Lumpur International Airport (KUL) - Malaysia", "Velana International Airport (MLE) - Maldives", "Tribhuvan International Airport (KTM) - Nepal", "Allama Iqbal International Airport (LHE) - Pakistan", "Jinnah International Airport (KHI) - Pakistan", "Hamad International Airport (DOH) - Qatar", "Sheremetyevo International Airport (SVO) - Russia", "King Abdulaziz International Airport (JED) - Saudi Arabia", "King Khalid International Airport (RUH) - Saudi Arabia", "Changi International Airport (SIN) - Singapore", "O.R. Tambo International Airport (JNB) - South Africa", "Bandaranaike International Airport (CMB) - Sri Lanka", "China Bay Airport (TRR) - Sri Lanka", "Jaffna International Airport (JAF) - Sri Lanka", "Mattala Rajapaksa International Airport (HRI) - Sri Lanka", "Victoria Reservoir Airfield (KDZ) -Sri Lanka", "Suvarnabhumi Airport (BKK) - Thailand", "Heathrow Airport (LHR) - United Kingdom", "Abu Dhabi International Airport (AUH) - UAE", "Dubai International Airport (DXB) - UAE" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Class");

        cmbClass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy Class", "Business Class" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Passengers");

        btnSearchFlight.setBackground(new java.awt.Color(0, 0, 153));
        btnSearchFlight.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchFlight.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchFlight.setText("Search Flight");
        btnSearchFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFlightActionPerformed(evt);
            }
        });

        tblFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "From Destination", "To Destination", "Departure Date", "Departure Time", "Arrival Date", "Arrival Time", "Class", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblFlights);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearchFlight)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(cmbTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbClass, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spPassengers)
                                .addComponent(cmbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnSearchFlight)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        VPassenger_Dashboard dashboard = new VPassenger_Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnFlightDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightDetailsActionPerformed
        VPassenger_View_Flight_Details fBooking = new VPassenger_View_Flight_Details();
        fBooking.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFlightDetailsActionPerformed

    private void btnSearchFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFlightActionPerformed
        searchFlights();
    }//GEN-LAST:event_btnSearchFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        SwingUtilities.invokeLater(() -> {
            new VPassenger_View_Flight_Details().setVisible(true);
        });
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPassenger_View_Flight_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFlightDetails;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSearchFlight;
    private javax.swing.JComboBox<String> cmbClass;
    private javax.swing.JComboBox<String> cmbFrom;
    private javax.swing.JComboBox<String> cmbTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spPassengers;
    private javax.swing.JTable tblFlights;
    // End of variables declaration//GEN-END:variables
}
